// Hitch: payment channels in a tab, Lightning-shaped. The node in the tab (browser/tabnode.js, pinned) funds, watches and
// settles; lib/channel.mjs builds and checks every transaction; lib/peer.mjs is the protocol, lib/route.mjs the routing;
// this file is the host: the relays, the chain, the coins, the window. Messages are signed, not encrypted.
const $ = (id) => document.getElementById(id);
const NODE = 'https://cdn.jsdelivr.net/gh/bitcoin-blake/blaketestnode@5befed46b68644185a24b00efb2aae749ffabb3d';
const LIB = 'https://cdn.jsdelivr.net/gh/sidestr/spec@fe689e9c723f9bf43393d2dd5b6f924a701c8a18/siding/lib', CDN = 'https://cdn.jsdelivr.net/gh/bitcoin-desktop/schema@v0.0.27';
const CHAIN = 'btc:testnet4-blake2b', KIND = 23600, BROADCAST_CHAIN = 'sidestr:tally', EXPLORER = 'https://mempool.guide/testnet4';
const DEFAULT_RELAYS = ['wss://relay.primal.net', 'wss://nostr.oxtr.dev', 'wss://nos.lol', 'wss://nostr.mom'];
const { createTabNode, n } = await import(`${NODE}/browser/tabnode.js`);
const { makeChannels, DEFAULT_DELAY, DEFAULT_FEE, DUST } = await import('./lib/channel.mjs'); const { makePeer, LIVE, WATCHED, TERMINAL, FOLLOWING, CLOSED_OUT, MIN_CONF, CLOSE_DEPTH } = await import('./lib/peer.mjs'); const { makeRouter } = await import('./lib/route.mjs');
const LS = { get: (k) => { try { return localStorage.getItem(k); } catch { return null; } }, set: (k, v) => { try { localStorage.setItem(k, v); return true; } catch { return false; } } };
const q = new URLSearchParams(location.search); if (q.get('embedded') === '1') document.body.classList.add('embedded');
const SNAP_URL = q.get('snapshot') ?? LS.get('hitch:snapshot') ?? LS.get('reef:snapshot') ?? 'https://melvin.me/public/txbt4/utxo-knots-150307.dat';
const BLOCKS_URL = q.get('blocks') ?? LS.get('hitch:blocks') ?? LS.get('reef:blocks') ?? 'https://melvin.me/public/txbt4/txbt4-blocks';
const OPT = (() => { const d = { relays: DEFAULT_RELAYS, delay: DEFAULT_DELAY, fee: DEFAULT_FEE, notify: false, dev: false }; try { return { ...d, ...JSON.parse(LS.get('hitch:options') ?? '{}') }; } catch { return d; } })();
const saveOptions = () => LS.set('hitch:options', JSON.stringify(OPT));
const money = (s) => (s / 1e8).toFixed(8) + ' tBTC'; const sats = (s) => `${n(s)} sat`; const now = () => Math.floor(Date.now() / 1000);
const fmt = (t) => new Date(t * 1000).toLocaleString(undefined, { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' });

// ---- log, notices, questions: every string from outside goes in as text, never as markup
const esc = (x) => String(x).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const LOG = []; function log(text, cls = '') { LOG.push([now(), String(text), cls]); if (LOG.length > 500) LOG.shift(); const line = (l) => `<div class="${l[2]}">${fmt(l[0])} ${esc(l[1])}</div>`; $('log').innerHTML = LOG.slice().reverse().map(line).join(''); $('recent').innerHTML = LOG.slice(-8).reverse().map(line).join('') || 'nothing yet'; }
let unseen = 0; function notify(title, body) { log(`${title}: ${body}`, 'b'); const el = document.createElement('div'); el.className = 'toast'; const b = document.createElement('b'); b.textContent = title; el.append(b, document.createElement('br'), document.createTextNode(body)); $('toasts').appendChild(el); setTimeout(() => { el.classList.add('out'); setTimeout(() => el.remove(), 400); }, 7000); if (OPT.notify && 'Notification' in window && Notification.permission === 'granted') new Notification(`Hitch · ${title}`, { body }); if (!$('tray').hidden) { unseen++; $('tray-badge').textContent = unseen; $('tray-badge').hidden = false; } }
// a question in the page (never a browser dialog): resolves true on the confirming button
function ask(title, lines, okLabel = 'OK', danger = false) { return new Promise((resolve) => { const d = $('ask'); $('ask-t').textContent = title; $('ask-b').innerHTML = lines.map((l) => `<p>${esc(l)}</p>`).join(''); const ok = $('ask-ok'); ok.textContent = okLabel; ok.classList.toggle('danger', danger); const done = (v) => { d.close(); ok.onclick = null; $('ask-cancel').onclick = null; resolve(v); }; ok.onclick = () => done(true); $('ask-cancel').onclick = () => done(false); d.onclose = () => resolve(false); d.showModal(); }); }
const hours = (blocks) => { const h = blocks * 20 / 60; return h < 1 ? `about ${Math.round(blocks * 20)} minutes` : h < 48 ? `about ${h.toFixed(h < 10 ? 1 : 0)} hours` : `about ${(h / 24).toFixed(1)} days`; };

// ---- the node in the tab
const tn = createTabNode({ base: NODE, snapshotUrl: SNAP_URL, blocksUrl: BLOCKS_URL }); const node = tn.node;
tn.on('sync', ({ msg, pct, eta }) => { $('syncmsg').textContent = msg; if (pct == null) { $('pb').hidden = true; $('synceta').textContent = ''; } else { $('pb').hidden = false; $('pbi').style.width = Math.max(0, Math.min(100, pct)).toFixed(1) + '%'; $('synceta').textContent = eta ? `${pct.toFixed(0)}% · ${eta}` : `${pct.toFixed(0)}%`; } $('ov-node').textContent = node.synced ? `up to date · ${n(node.height)}` : node.phase; });
tn.on('log', ({ text, level }) => { if (level === 'err') log(text, 'e'); });

// ---- channel documents and invoices, from this origin's storage
const CH = (() => { try { return JSON.parse(LS.get('hitch:channels') ?? '[]'); } catch { return []; } })();
const INV = (() => { try { return new Map(JSON.parse(LS.get('hitch:invoices') ?? '[]').map(([h, v]) => [h, typeof v === 'string' ? { preimage: v, amount: 0 } : v])); } catch { return new Map(); } })();
// ---- keys: Reef's when this browser has one, else Hitch's own; the same key signs channel transactions and relay messages
let W = null, C = null, R = null;
async function init() {
  const [{ makeSigner }, txsign, addr, relay, secp, hash, { createKernel }, { knotsBlake2b }, { verifyNostrEvent }] = await Promise.all([import(`${LIB}/schnorr.mjs`), import(`${LIB}/txsign.mjs`), import(`${LIB}/address.mjs`), import(`${LIB}/relay.mjs`), import(`${CDN}/codec/secp256k1.js`), import(`${CDN}/codec/hash.js`), import(`${CDN}/codec/kernel.js`), import(`${CDN}/codec/overlays/knots-blake2b.js`), import(`${CDN}/codec/nostr.js`)]);
  const j = async (p) => (await fetch(`${CDN}/${p}`)).json();
  const k = createKernel({ core: await j('schema/core.jsonld'), proof: await j('schema/proof.jsonld'), script: await j('schema/script.jsonld'), chain: await j('schema/chain.jsonld'), validate: await j('schema/validate.jsonld'), network: CHAIN, overlays: [knotsBlake2b(await j('schema/overlays/knots-blake2b.jsonld'))] });
  const signer = makeSigner({ hash, secp }); const HEX = /^[0-9a-f]{64}$/; const reef = LS.get('reef:key'), own = LS.get('hitch:key'); let key = (LS.get('hitch:prefer') === 'own' && HEX.test(own ?? '')) ? own : HEX.test(reef ?? '') ? reef : HEX.test(own ?? '') ? own : null; let persisted = true;
  // a live channel belongs to the key it was made with: that key wins over any newer one, and the page says so
  const owner = (kk) => signer.pubkeyOf(kk); const liveKey = [reef, own].filter((kk) => HEX.test(kk ?? '')).find((kk) => CH.some((c) => LIVE.has(c.status) && c.keys[c.role] === owner(kk)));
  if (liveKey && liveKey !== key) { log(`the key with live channels is kept, not the newer ${key === reef ? "Reef" : 'tab'} key; the channels are signed for by the key they were opened with`, 'e'); key = liveKey; }
  if (!key) { key = signer.randomKey(); persisted = LS.set('hitch:key', key); }
  const pub = signer.pubkeyOf(key), script = '5120' + pub; const events = relay.makeEvents({ signer, hash });
  W = { k, hash, secp, signer, txsign, key, pub, script, address: addr.scriptToAddress(script, 'tb'), fromReef: key === reef, coins: [], height: null, persisted };
  if (!persisted) { $('nokey').hidden = false; if (q.get('embedded') === '1') $('nokey').textContent = 'This pane\'s browser storage did not keep the key (storage is partitioned or blocked inside a host page). Open https://bitcoin-blake.github.io/hitch/ directly in a tab for a key that persists; nothing here can be funded safely.'; log('this browser did not keep the key (private window, storage blocked or full): nothing here can be funded safely; fix the storage and reload', 'e'); }
  C = makeChannels({ k, hash, secp, signer });
  R = { publish: (event) => relay.publish({ relays: OPT.relays, event }), sign: (o) => events.signEvent(key, o), parentTx: (hex) => events.parentTxEvent(signer.randomKey(), BROADCAST_CHAIN, hex), sockets: () => relay.sockets(), verify: verifyNostrEvent };
  $('ov-id').textContent = pub; $('ov-addr').textContent = W.address;
  log(`node id ${pub.slice(0, 16)}… (${W.fromReef ? "Reef's key" : 'a key of this tab'}); chain address ${W.address.slice(0, 16)}…`);
  R.sub = relay.subscribe({ relays: OPT.relays, chainId: CHAIN, kind: KIND, verify: verifyNostrEvent, since: 3600, log: (s) => log(s), onEvent: (ev) => onMessage(ev) });
}
function renderRelays() { if (!R) return; let s; try { s = R.sockets(); } catch { s = new Map(); } const parts = OPT.relays.map((u) => `${esc(u.replace('wss://', ''))} ${s.get(u) ? '<span class="good">connected</span>' : '<span class="bad">not connected</span>'}`); $('ov-relays').innerHTML = parts.join(' · '); }
setInterval(renderRelays, 5000);

// ---- channels: the protocol module holds the state machine; this page gives it the relays, the chain and the coins
const saveInv = () => LS.set('hitch:invoices', JSON.stringify([...INV]));
const PAY = (() => { try { return JSON.parse(LS.get('hitch:payments') ?? '[]'); } catch { return []; } })(); const savePay = () => { while (PAY.length > 50) PAY.shift(); LS.set('hitch:payments', JSON.stringify(PAY)); renderPayments(); };
const payRecord = (hash) => PAY.slice().reverse().find((x) => x.hash === hash);
function renderPayments() { const el = $('pay-list'); if (!el) return; el.innerHTML = PAY.length ? PAY.slice().reverse().map((x) => `<div class="payrow"><span class="mono">${fmt(x.at)}</span> <b>${sats(x.amount)}</b> to ${esc(x.to.slice(0, 12))}…${x.memo ? ` · ${esc(x.memo)}` : ''} on ${esc(x.ch)} <span class="st ${x.status === 'sent' ? 'open' : x.status === 'in flight' ? 'pend' : 'bad'}">${esc(x.status)}</span>${x.reason ? ` <span class="mut">${esc(x.reason)}</span>` : ''}</div>`).join('') : '<div class="mut">no payments yet</div>'; }
let P = null, ROUTER = null; const byId = (id) => CH.find((c) => c.id === id); const myBal = (ch) => P.myBal(ch), theirBal = (ch) => P.theirBal(ch);
const spendAsked = new Map(); // channel id → when; in memory only, so a reload asks again
// questions to the node worker that expect one answer, matched by a request id
const waiting = new Map(); let reqSeq = 0; const tnAsk = (type, body, ms = 120000) => new Promise((res) => { const req = `q${++reqSeq}`; const timer = setTimeout(() => { waiting.delete(req); res(null); }, ms); waiting.set(req, (m) => { clearTimeout(timer); res(m); }); tn.post({ type, ...body, req }); });
// coins held elsewhere: by a funding of ours not yet on the chain, and, when the key is Reef's, by a payment Reef made that is still waiting
const reefHeld = () => { if (!W?.fromReef) return []; try { return JSON.parse(LS.get('reef:sent:' + W.script.slice(4, 20)) ?? '[]').filter((x) => x.pending && !x.abandoned && !x.refused).flatMap((x) => x.inputs ?? []); } catch { return []; } };
const spentKeys = () => new Set([...CH.filter((c) => c.role === 'a' && ['proposed', 'accepted', 'funding', 'unfunded'].includes(c.status) && !c.cancelConfirmed).flatMap((c) => (c.funding.inputs ?? []).map((i) => i.key)), ...reefHeld()]);
const io = { get myScript() { return W.script; }, height: () => node.height ?? 0, stale: () => !node.synced, save: () => { const ok = LS.set('hitch:channels', JSON.stringify(CH)); render(); if (ok === false) { log('the tab could not save the channel state (storage full?): signatures and secrets are withheld until it can', 'e'); return false; } return true; }, log: (t, c) => log(t, c), notify: (t, b) => notify(t, b), invoiceFor: (h) => INV.get(h) ?? null,
  // the transaction that spent an output of a close, found by the node in the blocks since `from` (the walk remembered per output)
  findSpend: async (ch, { txid, vout, from }) => { ch.scanned ??= {}; const k2 = `${txid}:${vout}`; const s = ch.scanned[k2]; if (s?.found) return s.found; const m = await tnAsk('spend', { key: k2, from: Math.max(from, (s?.to ?? from) - 6) }); if (!m) return null; if (m.found) { const found = { txid: m.txid, height: m.height, hex: m.hex }; ch.scanned[k2] = { to: m.height, found }; return found; } ch.scanned[k2] = { to: m.to ?? from }; return null; },
  send: async (ch, body) => { const ev = R.sign({ kind: KIND, tags: [['chain', CHAIN], ['p', ch.peer], ['ch', ch.id]], content: JSON.stringify(body) }); const r = await R.publish(ev); const ok = Object.values(r).filter((x) => x === 'ok').length; if (!ok) log(`message ${body.t} reached no relay: ${JSON.stringify(r)}`, 'e'); return ok; },
  broadcast: async (hex, what) => { const r = await R.publish(R.parentTx(hex)); const ok = Object.values(r).filter((x) => x === 'ok').length; log(`${what} published to ${ok}/${OPT.relays.length} relays; a producer with a node broadcasts it`, ok ? '' : 'e'); return ok; },
  buildFunding: async (amount, spk) => { if (!node.synced) throw new Error('the node is not up to date yet'); const held = spentKeys(); const coins = W.coins.filter((c) => mature(c) && !held.has(c.key)).sort((x, y) => y.value - x.value); let picked = [], sum = 0, fee = 0; for (const c of coins) { picked.push(c); sum += c.value; fee = Math.ceil(11 + picked.length * 58 + 2 * 43); if (sum >= amount + fee) break; } if (sum < amount + fee) throw new Error(`not enough on-chain coins: ${sats(sum)} available, ${sats(amount + fee)} needed${W.coins.length === 0 ? ' (coins from before the snapshot are not seen by a tab)' : ''}`);
    if (!W.persisted) throw new Error('this browser did not keep the key; nothing can be funded safely');
    const change = sum - amount - fee; const ok = await ask('Open a channel', [`This spends ${sats(sum)} of ${W.fromReef ? "Reef's" : 'this tab\'s'} on-chain coins (${picked.length} coin${picked.length === 1 ? '' : 's'}): ${sats(amount)} into the channel, ${sats(fee)} in fees, ${sats(Math.max(0, change))} back as change.`, 'The funding goes out only after the other side has signed your first commitment. Nothing moves before that.', `While the channel is open this tab must be opened at least every ${hours(OPT.delay)} (the delay), or an old state published by the other side goes unpunished.`, W.fromReef ? "The key is Reef's: it is backed up if Reef's is." : 'Have you saved the key? Settings → Options shows it; without it the channel and its coins are lost with this browser profile.'], 'Open the channel'); if (!ok) throw new Error('cancelled');
    const outputs = [{ value: amount, scriptPubKey: spk }]; if (change >= DUST) outputs.push({ value: change, scriptPubKey: W.script }); else fee += change;
    const tx = { version: 2, inputs: picked.map((c) => ({ prevout: { txid: c.key.split(':')[0], vout: Number(c.key.split(':')[1]) }, scriptSig: '', sequence: 0xfffffffd })), outputs, lockTime: 0, witness: [] };
    W.txsign.signKeyPath({ k: W.k, hash: W.hash, signer: W.signer }, tx, picked.map((c) => ({ value: c.value, scriptPubKey: W.script })), W.key); for (const c of picked) W.coins = W.coins.filter((x) => x !== c); return { txid: C.txid(tx), vout: 0, hex: C.encode(tx), inputs: picked.map((c) => ({ key: c.key, value: c.value })) }; },
  onInvoicePaid: (h, amount) => { const i = INV.get(h); if (i) { i.paid = amount; saveInv(); } },
  onPayment: (ch, hash, outcome, reason) => { const r = payRecord(hash); if (!r) return; r.status = outcome; r.reason = reason ?? null; r.updated = now(); savePay(); if ($('pay-out').dataset.hash === hash) $('pay-out').textContent = `${sats(r.amount)} on ${r.ch}: ${outcome}${reason ? ` (${reason})` : ''}`; } };
function setupPeer() { P = makePeer({ C, signer: W.signer, hash: W.hash, pub: W.pub, key: W.key, channels: CH, io, opts: { delay: OPT.delay, fee: OPT.fee, minDelay: 6 } }); ROUTER = makeRouter({ peer: P, io, invoices: INV, hub: false }); const bg = (f) => (...a) => { f(...a).catch((e) => log(`router: ${e.message}`, 'e')); }; io.onUpdate = bg(ROUTER.onUpdate); io.onDropped = bg(ROUTER.onDropped); io.onPreimage = bg(ROUTER.onPreimage); window.hitch.P = P; setTimeout(() => P.resyncAll().catch((e) => log('resync: ' + e.message, 'e')), 4000); setInterval(() => P.tick().then(() => ROUTER.tick()).catch((e) => log('tick: ' + e.message, 'e')), 30000); }
async function onMessage(ev) { if (!W || !P) return; if (!ev?.tags?.some?.((t) => t[0] === 'p' && t[1] === W.pub)) return; let m = null; try { m = JSON.parse(ev.content); } catch { return; } try { await P.onMessage(ev.pubkey, m); } catch (e) { log(`message ${m?.t ?? '?'} for ${m?.id ?? '?'}: ${e.message}`, 'e'); } }
const openChannel = (peer, amount, push = 0) => P.openChannel(peer, amount, push);
async function cancelFunding(ch) { if (ch.role !== 'a' || !ch.funding.inputs?.length) throw new Error('only the funder can cancel, and only with the inputs on record'); const sum = ch.funding.inputs.reduce((a, c) => a + c.value, 0); const fundingFee = sum - C.decode(ch.funding.hex).outputs.reduce((a, o) => a + o.value, 0); const vsize = 11 + ch.funding.inputs.length * 58 + 43; const fee = Math.max(fundingFee + vsize * 2, vsize * 3); if (sum - fee < DUST) throw new Error('nothing left after the fee');
  if (!(await ask('Cancel the funding', [`This spends the ${ch.funding.inputs.length} coin(s) that funded ${ch.id} back to this key with a higher fee (${sats(fee)}), so the funding transaction can never confirm.`, 'If the funding confirms first anyway, the channel opens as usual; keep the channel until one or the other is in a block.'], 'Cancel the funding', true))) throw new Error('cancelled');
  const tx = { version: 2, inputs: ch.funding.inputs.map((c) => ({ prevout: { txid: c.key.split(':')[0], vout: Number(c.key.split(':')[1]) }, scriptSig: '', sequence: 0xfffffffd })), outputs: [{ value: sum - fee, scriptPubKey: W.script }], lockTime: 0, witness: [] };
  W.txsign.signKeyPath({ k: W.k, hash: W.hash, signer: W.signer }, tx, ch.funding.inputs.map((c) => ({ value: c.value, scriptPubKey: W.script })), W.key); ch.cancelTxid = C.txid(tx); ch.unsent = (ch.unsent ?? []).filter((u) => u.name !== 'funding'); ch.broadcastAt ??= now(); io.save(); const ok = await io.broadcast(C.encode(tx), `cancel of the funding of ${ch.id}`); if (!ok) { ch.unsent.push({ name: 'cancel', hex: C.encode(tx), txid: ch.cancelTxid }); io.save(); } log(`channel ${ch.id}: the funding is being cancelled by ${ch.cancelTxid.slice(0, 16)}…`); } const closeChannel = (ch) => P.closeChannel(ch); const forceClose = (ch, i, why) => P.forceClose(ch, i, why); const pay = (ch, amount, memo) => P.pay(ch, amount, memo);
// paying an invoice: an HTLC on a channel to the issuer, or to one of its hubs with the route; confirmed first
async function payInvoice(inv) { if (!node.synced) throw new Error('the node is not up to date yet'); if (Number.isInteger(inv.x) && now() > inv.x) throw new Error('the invoice has expired'); const expiry = io.height() + 60;
  const direct = CH.find((c) => c.status === 'open' && c.peer === inv.p && P.room(c) >= inv.a); let plan = direct ? { ch: direct, via: null, amount: inv.a } : null;
  if (!plan) for (const hub of inv.r ?? []) { const c = CH.find((x) => x.status === 'open' && x.peer === hub && P.room(x) >= inv.a + (x.peerHubFee ?? inv.f ?? 0)); if (c) { plan = { ch: c, via: hub, amount: inv.a + (c.peerHubFee ?? inv.f ?? 0) }; break; } }
  if (!plan) throw new Error('no open channel to that node or to one of its hubs with enough on my side');
  const ok = await ask('Pay this invoice', [`${sats(inv.a)} to ${inv.p.slice(0, 16)}…${inv.m ? ` for "${inv.m}"` : ''}.`, plan.via ? `Through ${plan.via.slice(0, 16)}… on channel ${plan.ch.id}, with a hub fee of ${sats(plan.amount - inv.a)}: ${sats(plan.amount)} in all.` : `Directly on channel ${plan.ch.id}.`, `The payment is an HTLC that expires at block ${n(expiry)}, 60 blocks from now (${hours(60)}); if the invoice is not settled by then the amount returns to you.${Number.isInteger(inv.x) ? ` The invoice itself expires ${fmt(inv.x)}.` : ''}`, 'Keep this tab open until the payment is reported sent or failed.'], 'Pay'); if (!ok) throw new Error('cancelled');
  await P.addHtlc(plan.ch, { amount: plan.amount, hash: inv.h, expiry, route: plan.via ? { to: inv.p } : null, memo: inv.m ?? null }); PAY.push({ hash: inv.h, amount: plan.amount, to: inv.p, memo: inv.m ?? null, ch: plan.ch.id, at: now(), status: 'in flight', reason: null }); savePay(); return plan; }

// ---- the chain: every funding output watched through the tab's own node, its value checked; a spend classified and answered by the protocol
const mature = (c) => !c.coinbase || (W.height != null && W.height + 1 - c.height >= 100);
function watch() { if (!W || !node.synced) return; tn.post({ type: 'coins', script: W.script }); for (const spk of new Set(CH.filter((c) => WATCHED.has(c.status)).map((c) => c.funding.spk))) tn.post({ type: 'coins', script: spk }); }
tn.on('coins', (m) => { if (!W) return; if (m.script === W.script) { W.coins = m.coins; W.height = m.height;
    for (const ch of CH) if (ch.cancelTxid) { const out = m.coins.find((c) => c.key === `${ch.cancelTxid}:0`); if (out && m.height - out.height + 1 >= CLOSE_DEPTH && !ch.cancelConfirmed) { ch.cancelConfirmed = out.height; io.save(); notify('Funding cancelled', `${ch.id}: the coins are back, ${CLOSE_DEPTH} blocks deep; the channel can be forgotten`); } else if (!out && ch.cancelConfirmed) { ch.cancelConfirmed = null; io.save(); log(`channel ${ch.id}: the cancelled coins are no longer in the chain (a reorganisation?); Forget is withheld`, 'e'); } } renderBalances(); return; }
  for (const ch of CH.filter((c) => c.funding.spk === m.script && WATCHED.has(c.status))) { const key = `${ch.funding.txid}:${ch.funding.vout}`; const coin = m.coins.find((c) => c.key === key);
    if (coin) { if (ch.spentBy) P.unSpend(ch); if (coin.value !== ch.funding.value) { if (ch.status !== 'bad-funding') { ch.status = 'bad-funding'; io.save(); log(`channel ${ch.id}: the funding output holds ${sats(coin.value)}, not the ${sats(ch.funding.value)} declared; refused`, 'e'); } continue; }
      const conf = m.height - coin.height + 1; if (conf < MIN_CONF) { ch.conf = conf; continue; } if (['funding', 'unfunded'].includes(ch.status)) { ch.status = 'open'; ch.fundedHeight = coin.height; io.save(); notify('Channel open', `${ch.id}: ${sats(ch.funding.value)} funded at block ${n(coin.height)}`); } else if (!ch.fundedHeight) { ch.fundedHeight = coin.height; io.save(); } ch.conf = conf; continue; }
    if (ch.fundedHeight && !ch.spentBy && (!spendAsked.has(ch.id) || now() - spendAsked.get(ch.id) > 60)) { spendAsked.set(ch.id, now()); tn.post({ type: 'spend', key, from: ch.fundedHeight, req: ch.id }); } }
  renderChannels(); });
tn.on('spend', async (m) => { if (typeof m.req === 'string' && waiting.has(m.req)) { const f = waiting.get(m.req); waiting.delete(m.req); f(m); return; }
  const ch = CH.find((c) => c.id === m.req); if (!ch) return; spendAsked.delete(ch.id); if (!m.found) return; try { await P.onSpend(ch, { txid: m.txid, height: m.height, blockHash: m.blockHash ?? null, hex: m.hex }); } catch (e) { log(`spend of ${ch.id}: ${e.message}`, 'e'); } });
let following = false;
tn.on('synced', async () => { if (!W || !P) return; watch(); if (!node.mempoolOn) { node.mempoolOn = true; tn.followMempool({ relays: OPT.relays }); } if (following) return; following = true; try { for (const ch of CH) if (FOLLOWING.has(ch.status)) await P.afterClose(ch).catch((e) => log(e.message, 'e')); } finally { following = false; } });

// ---- invoices: hitch1 + base64url of { p: node id, a: sats, m: memo, h: hash, r: hubs, f: hub fee, x: expires, i: id }; the preimage stays with the issuer
const b64u = (s) => btoa(unescape(encodeURIComponent(s))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); const unb64u = (s) => decodeURIComponent(escape(atob(s.replace(/-/g, '+').replace(/_/g, '/'))));
function makeInvoice(amount, memo) { if (!Number.isInteger(amount) || amount < 1000) throw new Error('at least 1,000 sat, a whole number'); const hubs = CH.filter((c) => c.status === 'open' && c.peerHubFee != null); const { preimage, inv } = P.invoice(amount, memo, [...new Set(hubs.map((c) => c.peer))], hubs.reduce((a, c) => Math.max(a, c.peerHubFee), 0)); INV.set(inv.h, { preimage, amount, memo: memo || undefined, x: inv.x }); saveInv(); return 'hitch1' + b64u(JSON.stringify(inv)); }
function parseInvoice(s) { s = s.trim(); if (!s.startsWith('hitch1')) throw new Error('not a Hitch invoice'); const inv = JSON.parse(unb64u(s.slice(6))); if (!/^[0-9a-f]{64}$/.test(inv.p ?? '') || !Number.isInteger(inv.a) || inv.a < 1 || !/^[0-9a-f]{64}$/.test(inv.h ?? '') || (inv.r != null && !(Array.isArray(inv.r) && inv.r.every((x) => /^[0-9a-f]{64}$/.test(x)))) || (inv.f != null && !(Number.isInteger(inv.f) && inv.f >= 0)) || (inv.x != null && !Number.isInteger(inv.x)) || (inv.m != null && !(typeof inv.m === 'string' && inv.m.length <= 140))) throw new Error('bad invoice'); return inv; }

// ---- rendering
const stLabel = (s) => ({ proposed: ['proposed', 'pend'], accepted: ['accepted, waiting for their signature', 'pend'], funding: ['funding, waiting for a block', 'pend'], open: ['open', 'open'], 'closing-asked': ['close asked', 'pend'], closing: ['closing', 'pend'], 'force-closing': ['force closing', 'pend'], 'closed-mine': ['closed by me, delay running', 'pend'], 'closed-coop': ['closed cooperatively, final after 6 blocks', 'pend'], 'closed-theirs': ['closed by them, claims running', 'pend'], 'closed-theirs-alt': ['closed by them at a state I had signed, claims running', 'pend'], closed: ['closed', 'closed'], settling: ['closed, claims confirming', 'pend'], unfunded: ['funding never confirmed; opens if it does', 'bad'], punishing: ['punishing a cheat', 'bad'], punished: ['closed: their cheat punished', 'closed'], 'spent-unknown': ['spent by an unknown transaction', 'bad'], 'bad-funding': ['funding output does not match: refused', 'bad'], abandoned: ['abandoned: never funded', 'closed'] }[s] ?? [s, '']);
const link = (txid, text) => `<a href="${EXPLORER}/tx/${esc(txid)}" target="_blank" rel="noopener" title="${esc(txid)}">${esc(text)}</a>`;
function renderChannels() { const el = $('chlist'); el.innerHTML = CH.length ? CH.slice().reverse().map((ch) => { const tot = ch.funding.value; const mine = myBal(ch), theirs = theirBal(ch); const [lbl0, cls] = stLabel(ch.status); const lbl = ch.cancelTxid && ['funding', 'unfunded'].includes(ch.status) ? (ch.cancelConfirmed ? 'funding cancelled, coins back' : 'funding being cancelled') : lbl0; const inflight = P.htlcs(ch);
    const note = ch.pending ? ' · update pending' : ch.awaiting ? ' · waiting for their revocation' : ''; const links = [link(ch.funding.txid, 'funding'), ch.cancelTxid ? link(ch.cancelTxid, 'cancel') : '', ch.closeTxid ? link(ch.closeTxid, 'close') : '', ch.coopTxid && ch.coopTxid !== ch.closeTxid ? link(ch.coopTxid, 'cooperative close') : '', ...(ch.penalties ?? []).map((p, i) => link(p, `penalty${ch.penalties.length > 1 ? ' ' + (i + 1) : ''}`)), ...Object.entries(ch.claimed ?? {}).map(([k2, v]) => link(v, k2.split(' ')[0]))].filter(Boolean).join(' · ');
    const buttons = ch.status === 'open' ? `<button class="q" data-act="close" data-ch="${esc(ch.id)}">Close</button><button class="q" data-act="force" data-ch="${esc(ch.id)}">Force close…</button>${OPT.dev && ch.n > 0 ? `<button class="q danger" data-act="cheat" data-ch="${esc(ch.id)}">Cheat (test)…</button>` : ''}` : ['closing-asked', 'closing'].includes(ch.status) ? `<button class="q" data-act="force" data-ch="${esc(ch.id)}">Force close…</button>` : (ch.status === 'unfunded' || (ch.status === 'funding' && now() - (ch.broadcastAt ?? now()) > 3600)) && ch.role === 'a' && ch.funding.inputs?.length && !ch.cancelTxid ? `<button class="q" data-act="cancel" data-ch="${esc(ch.id)}">Cancel the funding…</button>` : '';
    const forget = TERMINAL.has(ch.status) || (['unfunded', 'funding'].includes(ch.status) && (ch.role === 'b' ? ch.status === 'unfunded' : !!ch.cancelConfirmed)) ? `<button class="q" data-act="forget" data-ch="${esc(ch.id)}">Forget…</button>` : `<button class="q" data-act="abandon" data-ch="${esc(ch.id)}" title="remove from this tab; read the warning first">Abandon…</button>`;
    return `<div class="chan"><div class="hd"><b>${esc(ch.id)}</b><span class="st ${cls}">${esc(lbl)}</span><span class="mut">with ${esc(ch.peer.slice(0, 12))}… · ${ch.role === 'a' ? 'I funded' : 'they funded'} ${sats(tot)} · state ${ch.n}${ch.conf ? ` · ${ch.conf} conf` : ''}${esc(note)}${inflight.length ? ` · ${inflight.length} htlc in flight (${sats(inflight.reduce((a, h) => a + h.amount, 0))})` : ''}${ch.role === 'b' && ch.peerHubFee != null ? ' · a hub' : ''}</span></div>
    <div class="bar2" title="mine ${sats(mine)} · theirs ${sats(theirs)}"><i style="width:${(mine / tot * 100).toFixed(1)}%"></i><i class="r" style="width:${(theirs / tot * 100).toFixed(1)}%"></i></div>
    <div class="row" style="margin-top:6px;font-size:12px"><span>mine <b class="mono">${sats(mine)}</b></span><span class="mut">theirs ${sats(theirs)}</span><span class="mut">${links}</span><span class="fill" style="flex:1"></span>${buttons}${forget}</div></div>`; }).join('') : '<div class="mut">no channels yet: open one to another node id, or wait for one to be opened to you</div>';
  el.querySelectorAll('button[data-act]').forEach((b) => { b.onclick = async () => { const ch = byId(b.dataset.ch); if (!ch) return; try {
    if (b.dataset.act === 'close') await closeChannel(ch);
    else if (b.dataset.act === 'force') { const fl = P.htlcs(ch); if (await ask('Force close', [`This publishes your latest commitment (state ${ch.n}). Your ${sats(myBal(ch))} come back to your key after ${ch.delay} blocks (${hours(ch.delay)}); theirs at once. It costs ${sats(ch.fee)} in fees.`, ...(fl.length ? [`${fl.length} HTLC(s) in flight (${sats(fl.reduce((a, h) => a + h.amount, 0))}) are settled on the chain: claimed with the preimage or refunded after their expiry; keep the tab open until they are.`] : []), ...(ch.pending ? ['The update that is pending is set aside; if the other side acknowledged it late it could still take effect.'] : []), 'Use it when the other side is gone. A cooperative close is cheaper and faster when they answer.'], 'Force close', true)) await forceClose(ch); }
    else if (b.dataset.act === 'cheat') { if (await ask('Cheat, for the test', [`This publishes an OLD state (${ch.n - 1}) that you have revoked. If the other side is watching, it takes the whole channel: you lose ${sats(myBal(ch))}.`, 'This exists to show that cheating is punished.'], 'Publish the revoked state', true)) await forceClose(ch, ch.n - 1, 'CHEATING'); }
    else if (b.dataset.act === 'forget') { if (await ask('Forget this channel?', [`It is ${stLabel(ch.status)[0]}. Its record leaves this tab; export a backup first if you might need the details.`], 'Forget')) { CH.splice(CH.indexOf(ch), 1); io.save(); } }
    else if (b.dataset.act === 'cancel') await cancelFunding(ch);
    else if (b.dataset.act === 'abandon') { const lines = ch.status === 'closed-coop' ? [`It is ${stLabel(ch.status)[0]}. Until it is ${CLOSE_DEPTH} blocks deep a reorganisation could replace it with an old commitment, which this tab could then no longer punish.`, 'Wait for it to become closed, then Forget.'] : ['funding', 'unfunded'].includes(ch.status) && ch.role === 'a' ? [`It is ${stLabel(ch.status)[0]}. If the funding ever confirms after this record is gone, the ${sats(ch.funding.value)} are locked in a 2-of-2 output nobody can spend.`, 'Cancel the funding first (the button on the channel, an hour after the funding went out) and forget it once the cancel is confirmed.'] : [`It is ${stLabel(ch.status)[0]}. Removing it from this tab does not close it and does not return any funds.`, 'You lose the signed commitments and the revocation secrets: you can never force-close or claim from it again, and the other side can publish any old state without being punished.', 'Export a backup first if there is any doubt.']; if (await ask('Abandon this channel?', lines, 'Abandon', true)) { CH.splice(CH.indexOf(ch), 1); io.save(); } }
  } catch (e) { log(`${b.dataset.act} ${ch.id}: ${e.message}`, 'e'); } }; });
  $('push-ch').innerHTML = CH.filter((c) => c.status === 'open').map((c) => `<option value="${esc(c.id)}">${esc(c.id)} · mine ${sats(myBal(c))} · with ${esc(c.peer.slice(0, 10))}…</option>`).join('') || '<option value="">no open channel</option>';
  const busy = CH.some((c) => c.pending || c.awaiting || P.htlcs(c).length || CLOSED_OUT.has(c.status) || FOLLOWING.has(c.status)); const open = CH.filter((c) => c.status === 'open');
  $('keepopen').hidden = !busy && !open.length; $('keepopen').textContent = busy ? 'Keep this tab open: a payment is settling, an HTLC is in flight, or a close is being watched. A closed tab cannot punish a cheat or claim what is yours; both have deadlines measured in blocks.' : `A channel is open: come back to this tab well within ${hours(Math.max(1, Math.min(...open.map((c) => c.delay)) - 2))} each time (the channel delay, less the time a penalty needs to confirm). An old state published while the tab is closed for longer goes unpunished.`; renderBalances(); }
function renderBalances() { if (!W || !P) return; const open = CH.filter((c) => c.status === 'open'); const spendable = open.reduce((a, c) => a + (c.pending || c.awaiting ? 0 : Math.max(0, P.room(c))), 0), remote = open.reduce((a, c) => a + theirBal(c), 0);
  const inflight = open.reduce((a, c) => a + P.htlcs(c).filter((h) => h.from === c.role).reduce((x, h) => x + h.amount, 0), 0); const settling = CH.filter((c) => ['closing-asked', 'closing', 'force-closing', 'closed-mine', 'closed-theirs', 'closed-theirs-alt', 'punishing', 'settling'].includes(c.status)).reduce((a, c) => a + myBal(c), 0);
  let avail = 0, imm = 0; for (const c of W.coins) (mature(c) ? (avail += c.value) : (imm += c.value));
  const opening = CH.filter((c) => ['proposed', 'accepted', 'funding', 'unfunded'].includes(c.status) && c.role === 'a').reduce((a, c) => a + c.funding.value, 0);
  $('ch-local').textContent = money(spendable); $('ch-remote').textContent = money(remote); $('ch-flight').textContent = money(inflight); $('ch-settling').textContent = money(settling); $('ch-opening').textContent = money(opening); $('avail').textContent = money(avail); $('immature').textContent = money(imm); $('ch-count').textContent = `${open.length} open, ${CH.length} in all`; }
function render() { if (P) renderChannels(); else if (!SOLE) renderReadOnly(); }
function renderReadOnly() { $('chlist').innerHTML = CH.length ? CH.slice().reverse().map((ch) => `<div class="chan"><div class="hd"><b>${esc(ch.id)}</b><span class="st ${stLabel(ch.status)[1]}">${esc(stLabel(ch.status)[0])}</span><span class="mut">read-only: the other tab runs this channel</span></div></div>`).join('') : '<div class="mut">no channels</div>'; }
addEventListener('beforeunload', (e) => { if (!P) return; const busy = CH.some((c) => c.pending || c.awaiting || P.htlcs(c).length || CLOSED_OUT.has(c.status) || FOLLOWING.has(c.status)); if (busy) { e.preventDefault(); e.returnValue = ''; } });

// ---- the page
document.querySelectorAll('.tool button[data-p]').forEach((b) => { b.onclick = () => { document.querySelectorAll('.tool button[data-p]').forEach((x) => x.classList.toggle('on', x === b)); document.querySelectorAll('.page').forEach((p) => p.classList.toggle('on', p.id === 'p-' + b.dataset.p)); }; });
document.querySelectorAll('#menu > div').forEach((m) => { m.onkeydown = (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); m.click(); m.querySelector('.dd > div')?.focus(); } else if (e.key === 'Escape') m.classList.remove('open'); }; m.querySelectorAll('.dd > div').forEach((it) => { it.setAttribute('role', 'menuitem'); it.tabIndex = 0; it.onkeydown = (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); it.click(); } else if (e.key === 'Escape') { m.classList.remove('open'); m.focus(); } }; }); m.onclick = (e) => { const open = m.classList.contains('open'); document.querySelectorAll('#menu > div').forEach((x) => x.classList.remove('open')); if (!open && !e.target.closest('.dd')) m.classList.add('open'); }; }); document.addEventListener('click', (e) => { if (!e.target.closest('#menu')) document.querySelectorAll('#menu > div').forEach((x) => x.classList.remove('open')); });
$('op-go').onclick = async () => { try { $('op-out').textContent = 'proposing…'; await openChannel($('op-peer').value.trim().toLowerCase(), Math.round(Number($('op-amt').value)), Math.round(Number($('op-push').value) || 0)); $('op-out').textContent = 'proposed; waiting for the other side'; } catch (e) { $('op-out').textContent = e.message; } };
$('push-go').onclick = async () => { try { const ch = byId($('push-ch').value); if (!ch) throw new Error('no open channel'); const amount = Math.round(Number($('push-amt').value)); if (!(await ask('Push to the channel', [`${sats(amount)} to ${ch.peer.slice(0, 16)}… on ${ch.id}, with no invoice: the other side just gets it.`], 'Push'))) return; await pay(ch, amount, $('push-memo').value.trim() || null); $('push-out').textContent = 'update sent; it is final when they acknowledge and you revoke'; } catch (e) { $('push-out').textContent = e.message; } };
$('pay-go').onclick = async () => { try { const inv = parseInvoice($('pay-inv').value); if (['sent', 'in flight'].includes(payRecord(inv.h)?.status)) throw new Error(`that invoice is already ${payRecord(inv.h).status} from this tab`); const r = await payInvoice(inv); $('pay-out').dataset.hash = inv.h; $('pay-out').textContent = `paying ${sats(r.amount)} on ${r.ch.id}${r.via ? ` through ${r.via.slice(0, 12)}…` : ''}: the HTLC is out; the outcome shows here and in the list below`; } catch (e) { $('pay-out').dataset.hash = ''; $('pay-out').textContent = e.message; } };
$('pay-paste').onclick = async () => { try { $('pay-inv').value = await navigator.clipboard.readText(); } catch {} };
$('inv-go').onclick = () => { try { const s = makeInvoice(Math.round(Number($('inv-amt').value)), $('inv-memo').value.trim()); $('inv-out').value = s; const qr = qrcode(0, 'M'); qr.addData(s); qr.make(); $('inv-qr').innerHTML = qr.createSvgTag({ cellSize: 3, margin: 0 }); } catch (e) { $('inv-out').value = e.message; } };
$('inv-copy').onclick = async () => { try { await navigator.clipboard.writeText($('inv-out').value); $('inv-copy').textContent = 'Copied'; setTimeout(() => { $('inv-copy').textContent = 'Copy'; }, 1500); } catch {} };
$('m-nodeid').onclick = async () => { try { await navigator.clipboard.writeText(W.pub); notify('Copied', 'this node id is on the clipboard'); } catch {} };
$('m-readme').onclick = () => window.open('https://github.com/bitcoin-blake/hitch#readme', '_blank', 'noopener'); $('m-source').onclick = () => window.open('https://github.com/bitcoin-blake/hitch', '_blank', 'noopener');
$('m-about').onclick = () => $('about').showModal(); $('about-ok').onclick = () => $('about').close();
// ---- the window: dragged by its title bar, resized at any edge, zoomed by the green dot; geometry remembered; the tray when closed or minimized
const win = $('win'); const embedded = q.get('embedded') === '1' || q.get('frame') === '0';
const geom = { get: () => { try { return JSON.parse(LS.get('hitch:geometry') ?? 'null'); } catch { return null; } }, set: (g) => LS.set('hitch:geometry', JSON.stringify(g)) };
function applyGeometry(g) { win.style.left = g.x + 'px'; win.style.top = g.y + 'px'; win.style.width = g.w + 'px'; win.style.height = g.h + 'px'; }
function clampGeometry(g) { const W = innerWidth, H = innerHeight; g.w = Math.max(720, Math.min(g.w, W)); g.h = Math.max(420, Math.min(g.h, H)); g.x = Math.max(0, Math.min(g.x, W - Math.min(g.w, 120))); g.y = Math.max(0, Math.min(g.y, H - 40)); return g; }
function defaultGeometry() { const w = Math.min(1180, innerWidth - 48), h = Math.min(780, innerHeight - 48); return { x: Math.round((innerWidth - w) / 2), y: Math.round((innerHeight - h) / 2), w, h }; }
function layoutWindow() { if (embedded) return; const small = innerWidth < 1100 || innerHeight < 700; const saved = geom.get(); const max = saved?.max ?? small; win.classList.toggle('max', max); if (!max) applyGeometry(clampGeometry(saved?.g ?? defaultGeometry())); }
function saveGeometry() { if (embedded) return; const max = win.classList.contains('max'); const g = max ? (geom.get()?.g ?? defaultGeometry()) : { x: win.offsetLeft, y: win.offsetTop, w: win.offsetWidth, h: win.offsetHeight }; geom.set({ max, g }); }
function toggleZoom() { if (embedded) return; const max = !win.classList.contains('max'); win.classList.toggle('max', max); if (!max) applyGeometry(clampGeometry(geom.get()?.g ?? defaultGeometry())); saveGeometry(); }
if (!embedded) {
  layoutWindow(); addEventListener('resize', () => { if (!win.classList.contains('max')) applyGeometry(clampGeometry({ x: win.offsetLeft, y: win.offsetTop, w: win.offsetWidth, h: win.offsetHeight })); });
  $('dot-zoom').onclick = (e) => { e.stopPropagation(); toggleZoom(); }; $('wtitle').ondblclick = (e) => { if (!e.target.closest('.dots, .badge')) toggleZoom(); }; $('dot-close').onclick = (e) => { e.stopPropagation(); hideWindow(); }; $('dot-min').onclick = (e) => { e.stopPropagation(); hideWindow(); };
  // drag by the title bar
  $('wtitle').onpointerdown = (e) => { if (win.classList.contains('max') || e.target.closest('.dots, .badge')) return; const sx = e.clientX - win.offsetLeft, sy = e.clientY - win.offsetTop; const move = (ev) => applyGeometry(clampGeometry({ x: ev.clientX - sx, y: ev.clientY - sy, w: win.offsetWidth, h: win.offsetHeight })); const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); saveGeometry(); }; addEventListener('pointermove', move); addEventListener('pointerup', up); e.preventDefault(); };
  // resize at any edge or corner
  win.querySelectorAll(':scope > .rs').forEach((h) => { h.onpointerdown = (e) => { if (win.classList.contains('max')) return; const d = h.dataset.rs, x0 = e.clientX, y0 = e.clientY, g0 = { x: win.offsetLeft, y: win.offsetTop, w: win.offsetWidth, h: win.offsetHeight };
    const move = (ev) => { const dx = ev.clientX - x0, dy = ev.clientY - y0; const g = { ...g0 }; if (d.includes('e')) g.w = g0.w + dx; if (d.includes('s')) g.h = g0.h + dy; if (d.includes('w')) { g.w = g0.w - dx; g.x = g0.x + dx; } if (d.includes('n')) { g.h = g0.h - dy; g.y = g0.y + dy; } if (g.w < 720) { if (d.includes('w')) g.x = g0.x + g0.w - 720; g.w = 720; } if (g.h < 420) { if (d.includes('n')) g.y = g0.y + g0.h - 420; g.h = 420; } applyGeometry(g); };
    const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); saveGeometry(); }; addEventListener('pointermove', move); addEventListener('pointerup', up); e.preventDefault(); e.stopPropagation(); }; });
}

// ---- the tray: closing or minimizing the window keeps the node running and leaves a small card to come back through (Knots goes to the system tray the same way); inside Glass the host is told and keeps its dock
function hideWindow() { if (embedded) { try { parent.postMessage({ source: 'hitch', type: 'minimize' }, '*'); } catch {} return; } win.style.display = 'none'; unseen = 0; $('tray-badge').hidden = true; $('tray').hidden = false; trayRefresh(); }
function showWindow() { win.style.display = ''; $('tray').hidden = true; unseen = 0; $('tray-badge').hidden = true; }
function trayRefresh() { if ($('tray').hidden) return; const open = CH.filter((c) => c.status === 'open'); const sd = open.length ? ` · ${open.length} channel${open.length === 1 ? '' : 's'}, ${sats(open.reduce((a, c) => a + myBal(c), 0))}` : ''; $('tray-l').textContent = node.error ? 'error' : node.synced ? `up to date · ${n(node.height)}${sd}` : node.phase === 'fetch' ? 'fetching the snapshot' : node.phase === 'hash' ? 'checking the snapshot' : node.phase === 'verify' ? 'verifying the snapshot' : node.phase === 'sync' ? `syncing · ${n(node.height ?? 0)}` : 'starting'; $('tray-dot').className = node.error ? 'bad' : node.synced ? 'ok' : 'sync'; }
$('tray').onclick = () => showWindow(); $('tray').onkeydown = (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); showWindow(); } }; setInterval(trayRefresh, 1000);

$('m-exit').onclick = () => hideWindow(); $('m-zoom').onclick = () => toggleZoom(); $('m-main').onclick = () => showWindow(); document.addEventListener('keydown', (e) => { if (e.ctrlKey && !e.shiftKey && e.key.toLowerCase() === 'm') { e.preventDefault(); showWindow(); } });
$('m-readme').onclick = () => window.open('https://github.com/bitcoin-blake/hitch#readme', '_blank', 'noopener'); $('m-source').onclick = () => window.open('https://github.com/bitcoin-blake/hitch', '_blank', 'noopener');
$('m-about').onclick = () => $('about').showModal(); $('about-ok').onclick = () => $('about').close();
$('m-options').onclick = () => { $('o-relays').value = OPT.relays.join('\n'); $('o-delay').value = OPT.delay; $('o-delayh').textContent = hours(OPT.delay); $('o-fee').value = OPT.fee; $('o-notify').checked = !!OPT.notify; $('o-dev').checked = !!OPT.dev; $('o-snapshot').value = SNAP_URL; $('o-blocks').value = BLOCKS_URL; $('o-address').value = W?.address ?? '…'; $('o-key').value = '•'.repeat(64); $('o-showkey').textContent = 'Show'; $('o-importkey').value = ''; $('o-keynote').textContent = W?.fromReef ? "Reef's key in this browser: back it up in Reef" : 'a key of this tab: copy it somewhere safe, the export below does not include it'; $('o-note').textContent = ''; $('options').showModal(); };
$('o-delay').oninput = () => { $('o-delayh').textContent = hours(Number($('o-delay').value) || 0); };
$('o-cancel').onclick = () => $('options').close();
$('o-showkey').onclick = () => { const shown = $('o-key').value !== '•'.repeat(64); $('o-key').value = shown ? '•'.repeat(64) : (W?.key ?? ''); $('o-showkey').textContent = shown ? 'Show' : 'Hide'; };
$('o-copykey').onclick = async () => { try { await navigator.clipboard.writeText(W?.key ?? ''); $('o-copykey').textContent = 'Copied'; setTimeout(() => { $('o-copykey').textContent = 'Copy'; }, 1500); } catch {} };
$('o-export').onclick = async () => { if (!(await ask('Export the channel documents', ['The file holds every signed commitment, every revocation secret and every preimage. Anyone who reads it can take what is yours in these channels. It does not hold the key.', 'Keep it where only you can read it.'], 'Export'))) return; const blob = new Blob([JSON.stringify({ hitch: 1, exported: now(), node: W.pub, channels: CH, invoices: [...INV] }, null, 1)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `hitch-channels-SECRET-${W.pub.slice(0, 8)}-${new Date().toISOString().slice(0, 10)}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 2000); };
$('o-import').onchange = async () => { const f = $('o-import').files[0]; if (!f) return; try { const d = JSON.parse(await f.text()); if (d.hitch !== 1 || !Array.isArray(d.channels)) throw new Error('not a Hitch backup'); if (d.node && d.node !== W.pub) throw new Error(`that backup is for node ${d.node.slice(0, 12)}…, this tab is ${W.pub.slice(0, 12)}…`); let added = 0, newer = 0; for (const c of d.channels) { const have = byId(c.id); if (!have) { CH.push(c); added++; } else if ((c.n ?? 0) > (have.n ?? 0)) { Object.assign(have, c); newer++; } } for (const [h, p] of d.invoices ?? []) if (!INV.has(h)) INV.set(h, typeof p === 'string' ? { preimage: p, amount: 0 } : p); saveInv(); io.save(); $('o-note').textContent = `imported: ${added} new channel(s), ${newer} brought forward; resyncing`; log(`backup imported: ${added} new, ${newer} newer`); P.resyncAll(true).catch(() => {}); } catch (e) { $('o-note').textContent = e.message; } };
$('o-ok').onclick = async () => { const relays = $('o-relays').value.split(/\s+/).filter((r) => /^wss?:\/\//.test(r)); OPT.relays = relays.length ? relays : DEFAULT_RELAYS; OPT.delay = Math.max(6, Math.min(144, Math.round(Number($('o-delay').value) || DEFAULT_DELAY))); OPT.fee = Math.max(100, Math.min(10000, Math.round(Number($('o-fee').value) || DEFAULT_FEE))); OPT.dev = $('o-dev').checked; const wantNotify = $('o-notify').checked; if (wantNotify && 'Notification' in window && Notification.permission === 'default') await Notification.requestPermission(); OPT.notify = wantNotify && Notification.permission === 'granted'; saveOptions();
  const s = $('o-snapshot').value.trim(), b = $('o-blocks').value.trim(); if (s) LS.set('hitch:snapshot', s); if (b) LS.set('hitch:blocks', b); const key = $('o-importkey').value.trim().toLowerCase(); if (key && !/^[0-9a-f]{64}$/.test(key)) { $('o-note').textContent = 'a key is 64 hex characters'; return; }
  if (key) { if (CH.some((c) => (LIVE.has(c.status) || WATCHED.has(c.status)) && c.keys[c.role] === W.pub)) { $('o-note').textContent = 'this tab has channels made with the current key that are open or still being watched; close and settle them first, or export them'; return; } if ($('o-key').value === '•'.repeat(64)) { $('o-note').textContent = 'show or copy the current key first: it is the only way back to it'; return; } if (!(await ask('Replace the key', ['The current key stays where it is (in Reef, if it is Reef\'s) but this tab stops using it. Channels in this tab that belong to another key cannot be signed for.'], 'Replace', true))) return; LS.set('hitch:key', key); LS.set('hitch:prefer', 'own'); }
  $('options').close(); location.search = embedded ? (q.get('frame') === '0' ? '?frame=0' : '?embedded=1') : ''; };
window.hitch = { tn, node, CH, INV, get W() { return W; }, get C() { return C; }, pay, openChannel, closeChannel, forceClose, payInvoice, makeInvoice };
// one tab of this origin runs the protocol; a second one would sign with its own fresh points over the same documents and wedge the channels
let SOLE = true; if (navigator.locks) { await new Promise((res) => navigator.locks.request('hitch:peer', { ifAvailable: true }, (lock) => { SOLE = !!lock; res(); return lock ? new Promise(() => {}) : undefined; }).catch(() => res())); }
try { await init(); if (SOLE) setupPeer(); else { $('twotabs').hidden = false; log('another tab of Hitch is running on this origin: this one is read-only (close the other one and reload to take over)', 'e'); document.querySelectorAll('#op-go, #push-go, #pay-go, #inv-go, #chlist').forEach((el) => { el.classList.add('ro'); }); } } catch (e) { log('could not start: ' + e.message, 'e'); }
if (!SOLE) addEventListener('storage', (e) => { if (e.key === 'hitch:channels') { try { const fresh = JSON.parse(e.newValue ?? '[]'); CH.splice(0, CH.length, ...fresh); } catch {} } });
document.querySelectorAll('label').forEach((l) => { if (l.htmlFor || l.querySelector('input')) return; const nx = l.nextElementSibling; const inp = nx?.matches?.('input,textarea,select') ? nx : nx?.querySelector?.('input,textarea,select'); if (inp?.id) l.htmlFor = inp.id; });
render(); renderRelays(); renderPayments(); log('Hitch started');
try { if (await tn.start() === false) $('syncmsg').textContent = 'idle: the node runs in another tab of this browser (Reef, Bight, Winch or Hitch); close that tab and reload here'; } catch (e) { $('syncmsg').textContent = 'Error: could not start the node: ' + e.message; }
