// Hitch: payment channels in a tab, Lightning-shaped. The node in the tab (browser/tabnode.js, pinned) funds, watches and
// settles; lib/channel.mjs builds and checks every transaction; lib/peer.mjs is the protocol, lib/route.mjs the routing;
// this file is the host: the relays, the chain, the coins, the window. Messages are signed, not encrypted.
const $ = (id) => document.getElementById(id);
const NODE = 'https://cdn.jsdelivr.net/gh/bitcoin-blake/blaketestnode@f43417b6c53bda007487a8d7738a848c0e6d3792';
const LIB = 'https://cdn.jsdelivr.net/gh/sidestr/spec@fe689e9c723f9bf43393d2dd5b6f924a701c8a18/siding/lib', CDN = 'https://cdn.jsdelivr.net/gh/bitcoin-desktop/schema@v0.0.27';
const CHAIN = 'btc:testnet4-blake2b', KIND = 23600, BROADCAST_CHAIN = 'sidestr:tally', EXPLORER = 'https://mempool.guide/testnet4';
const DEFAULT_RELAYS = ['wss://relay.primal.net', 'wss://nostr.oxtr.dev', 'wss://nos.lol', 'wss://nostr.mom'];
const { createTabNode, n } = await import(`${NODE}/browser/tabnode.js`);
const { makeChannels, DEFAULT_DELAY, DEFAULT_FEE, DUST } = await import('./lib/channel.mjs'); const { makePeer, LIVE, WATCHED } = await import('./lib/peer.mjs'); const { makeRouter } = await import('./lib/route.mjs');
const LS = { get: (k) => { try { return localStorage.getItem(k); } catch { return null; } }, set: (k, v) => { try { localStorage.setItem(k, v); return true; } catch { return false; } } };
const q = new URLSearchParams(location.search); if (q.get('embedded') === '1') document.body.classList.add('embedded');
const SNAP_URL = q.get('snapshot') ?? LS.get('hitch:snapshot') ?? LS.get('reef:snapshot') ?? 'https://melvin.me/public/txbt4/utxo-knots-150307.dat';
const BLOCKS_URL = q.get('blocks') ?? LS.get('hitch:blocks') ?? LS.get('reef:blocks') ?? 'https://melvin.me/public/txbt4/txbt4-blocks';
const OPT = (() => { const d = { relays: DEFAULT_RELAYS, delay: DEFAULT_DELAY, fee: DEFAULT_FEE, notify: false, dev: false }; try { return { ...d, ...JSON.parse(LS.get('hitch:options') ?? '{}') }; } catch { return d; } })();
const saveOptions = () => LS.set('hitch:options', JSON.stringify(OPT));
const money = (s) => (s / 1e8).toFixed(8) + ' tBTC'; const sats = (s) => `${n(s)} sat`; const now = () => Math.floor(Date.now() / 1000);
const fmt = (t) => new Date(t * 1000).toLocaleString(undefined, { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' });

// ---- log, notices, questions: every string from outside goes in as text, never as markup
const esc = (x) => String(x).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const LOG = []; function log(text, cls = '') { LOG.push([now(), String(text), cls]); if (LOG.length > 500) LOG.shift(); const line = (l) => `<div class="${l[2]}">${fmt(l[0])} ${esc(l[1])}</div>`; $('log').innerHTML = LOG.slice().reverse().map(line).join(''); $('recent').innerHTML = LOG.slice(-8).reverse().map(line).join('') || 'nothing yet'; }
let unseen = 0; function notify(title, body) { log(`${title}: ${body}`, 'b'); const el = document.createElement('div'); el.className = 'toast'; const b = document.createElement('b'); b.textContent = title; el.append(b, document.createElement('br'), document.createTextNode(body)); $('toasts').appendChild(el); setTimeout(() => { el.classList.add('out'); setTimeout(() => el.remove(), 400); }, 7000); if (OPT.notify && 'Notification' in window && Notification.permission === 'granted') new Notification(`Hitch · ${title}`, { body }); if (!$('tray').hidden) { unseen++; $('tray-badge').textContent = unseen; $('tray-badge').hidden = false; } }
// a question in the page (never a browser dialog): resolves true on the confirming button
function ask(title, lines, okLabel = 'OK', danger = false) { return new Promise((resolve) => { const d = $('ask'); $('ask-t').textContent = title; $('ask-b').innerHTML = lines.map((l) => `<p>${esc(l)}</p>`).join(''); const ok = $('ask-ok'); ok.textContent = okLabel; ok.classList.toggle('danger', danger); const done = (v) => { d.close(); ok.onclick = null; $('ask-cancel').onclick = null; resolve(v); }; ok.onclick = () => done(true); $('ask-cancel').onclick = () => done(false); d.onclose = () => resolve(false); d.showModal(); }); }
const hours = (blocks) => { const h = blocks * 20 / 60; return h < 1 ? `about ${Math.round(blocks * 20)} minutes` : h < 48 ? `about ${h.toFixed(h < 10 ? 1 : 0)} hours` : `about ${(h / 24).toFixed(1)} days`; };

// ---- the node in the tab
const tn = createTabNode({ base: NODE, snapshotUrl: SNAP_URL, blocksUrl: BLOCKS_URL }); const node = tn.node;
tn.on('sync', ({ msg, pct, eta }) => { $('syncmsg').textContent = msg; if (pct == null) { $('pb').hidden = true; $('synceta').textContent = ''; } else { $('pb').hidden = false; $('pbi').style.width = Math.max(0, Math.min(100, pct)).toFixed(1) + '%'; $('synceta').textContent = eta ? `${pct.toFixed(0)}% · ${eta}` : `${pct.toFixed(0)}%`; } $('ov-node').textContent = node.synced ? `up to date · ${n(node.height)}` : node.phase; });
tn.on('log', ({ text, level }) => { if (level === 'err') log(text, 'e'); });

// ---- keys: Reef's when this browser has one, else Hitch's own; the same key signs channel transactions and relay messages
let W = null, C = null, R = null;
async function init() {
  const [{ makeSigner }, txsign, addr, relay, secp, hash, { createKernel }, { knotsBlake2b }, { verifyNostrEvent }] = await Promise.all([import(`${LIB}/schnorr.mjs`), import(`${LIB}/txsign.mjs`), import(`${LIB}/address.mjs`), import(`${LIB}/relay.mjs`), import(`${CDN}/codec/secp256k1.js`), import(`${CDN}/codec/hash.js`), import(`${CDN}/codec/kernel.js`), import(`${CDN}/codec/overlays/knots-blake2b.js`), import(`${CDN}/codec/nostr.js`)]);
  const j = async (p) => (await fetch(`${CDN}/${p}`)).json();
  const k = createKernel({ core: await j('schema/core.jsonld'), proof: await j('schema/proof.jsonld'), script: await j('schema/script.jsonld'), chain: await j('schema/chain.jsonld'), validate: await j('schema/validate.jsonld'), network: CHAIN, overlays: [knotsBlake2b(await j('schema/overlays/knots-blake2b.jsonld'))] });
  const signer = makeSigner({ hash, secp }); const reef = LS.get('reef:key'); let key = /^[0-9a-f]{64}$/.test(reef ?? '') ? reef : LS.get('hitch:key'); if (!/^[0-9a-f]{64}$/.test(key ?? '')) { key = signer.randomKey(); LS.set('hitch:key', key); }
  const pub = signer.pubkeyOf(key), script = '5120' + pub; const events = relay.makeEvents({ signer, hash });
  W = { k, hash, secp, signer, txsign, key, pub, script, address: addr.scriptToAddress(script, 'tb'), fromReef: key === reef, coins: [], height: null };
  C = makeChannels({ k, hash, secp, signer });
  R = { publish: (event) => relay.publish({ relays: OPT.relays, event }), sign: (o) => events.signEvent(key, o), parentTx: (hex) => events.parentTxEvent(signer.randomKey(), BROADCAST_CHAIN, hex), sockets: () => relay.sockets(), verify: verifyNostrEvent };
  $('ov-id').textContent = pub; $('ov-addr').textContent = W.address;
  log(`node id ${pub.slice(0, 16)}… (${W.fromReef ? "Reef's key" : 'a key of this tab'}); chain address ${W.address.slice(0, 16)}…`);
  R.sub = relay.subscribe({ relays: OPT.relays, chainId: CHAIN, kind: KIND, verify: verifyNostrEvent, since: 3600, log: (s) => log(s), onEvent: (ev) => onMessage(ev) });
}
function renderRelays() { if (!R) return; let s; try { s = R.sockets(); } catch { s = new Map(); } const parts = OPT.relays.map((u) => `${esc(u.replace('wss://', ''))} ${s.get(u) ? '<span class="good">connected</span>' : '<span class="bad">not connected</span>'}`); $('ov-relays').innerHTML = parts.join(' · '); }
setInterval(renderRelays, 5000);

// ---- channels: the protocol module holds the state machine; this page gives it the relays, the chain and the coins
const CH = (() => { try { return JSON.parse(LS.get('hitch:channels') ?? '[]'); } catch { return []; } })();
const INV = (() => { try { return new Map(JSON.parse(LS.get('hitch:invoices') ?? '[]').map(([h, v]) => [h, typeof v === 'string' ? { preimage: v, amount: 0 } : v])); } catch { return new Map(); } })();
const saveInv = () => LS.set('hitch:invoices', JSON.stringify([...INV]));
let P = null, ROUTER = null; const byId = (id) => CH.find((c) => c.id === id); const myBal = (ch) => P.myBal(ch), theirBal = (ch) => P.theirBal(ch);
const spendAsked = new Map(); // channel id → when; in memory only, so a reload asks again
const io = { get myScript() { return W.script; }, height: () => node.height ?? 0, save: () => { const ok = LS.set('hitch:channels', JSON.stringify(CH)); if (ok === false) { log('the tab could not save the channel state (storage full?); do not make further updates until it can', 'e'); } render(); }, log: (t, c) => log(t, c), notify: (t, b) => notify(t, b), invoiceFor: (h) => INV.get(h) ?? null,
  send: async (ch, body) => { const ev = R.sign({ kind: KIND, tags: [['chain', CHAIN], ['p', ch.peer], ['ch', ch.id]], content: JSON.stringify(body) }); const r = await R.publish(ev); const ok = Object.values(r).filter((x) => x === 'ok').length; if (!ok) log(`message ${body.t} reached no relay: ${JSON.stringify(r)}`, 'e'); return ok; },
  broadcast: async (hex, what) => { const r = await R.publish(R.parentTx(hex)); const ok = Object.values(r).filter((x) => x === 'ok').length; log(`${what} published to ${ok}/${OPT.relays.length} relays; a producer with a node broadcasts it`, ok ? '' : 'e'); return ok; },
  buildFunding: async (amount, spk) => { if (!node.synced) throw new Error('the node is not up to date yet'); const coins = W.coins.filter((c) => mature(c)).sort((x, y) => y.value - x.value); let picked = [], sum = 0, fee = 0; for (const c of coins) { picked.push(c); sum += c.value; fee = Math.ceil(11 + picked.length * 58 + 2 * 43); if (sum >= amount + fee) break; } if (sum < amount + fee) throw new Error(`not enough on-chain coins: ${sats(sum)} available, ${sats(amount + fee)} needed${W.coins.length === 0 ? ' (coins from before the snapshot are not seen by a tab)' : ''}`);
    const change = sum - amount - fee; const ok = await ask('Open a channel', [`This spends ${sats(sum)} of ${W.fromReef ? "Reef's" : 'this tab\'s'} on-chain coins (${picked.length} coin${picked.length === 1 ? '' : 's'}): ${sats(amount)} into the channel, ${sats(fee)} in fees, ${sats(Math.max(0, change))} back as change.`, 'The funding goes out only after the other side has signed your first commitment. Nothing moves before that.'], 'Open the channel'); if (!ok) throw new Error('cancelled');
    const outputs = [{ value: amount, scriptPubKey: spk }]; if (change >= DUST) outputs.push({ value: change, scriptPubKey: W.script }); else fee += change;
    const tx = { version: 2, inputs: picked.map((c) => ({ prevout: { txid: c.key.split(':')[0], vout: Number(c.key.split(':')[1]) }, scriptSig: '', sequence: 0xfffffffd })), outputs, lockTime: 0, witness: [] };
    W.txsign.signKeyPath({ k: W.k, hash: W.hash, signer: W.signer }, tx, picked.map((c) => ({ value: c.value, scriptPubKey: W.script })), W.key); for (const c of picked) W.coins = W.coins.filter((x) => x !== c); return { txid: C.txid(tx), vout: 0, hex: C.encode(tx) }; },
  onInvoicePaid: (h, amount) => { const i = INV.get(h); if (i) { i.paid = amount; saveInv(); } } };
function setupPeer() { P = makePeer({ C, signer: W.signer, hash: W.hash, pub: W.pub, key: W.key, channels: CH, io, opts: { delay: OPT.delay, fee: OPT.fee, minDelay: 6 } }); ROUTER = makeRouter({ peer: P, io, invoices: INV, hub: false }); io.onUpdate = ROUTER.onUpdate; window.hitch.P = P; setTimeout(() => P.resyncAll().catch((e) => log('resync: ' + e.message, 'e')), 4000); setInterval(() => P.tick().then(() => ROUTER.tick()).catch((e) => log('tick: ' + e.message, 'e')), 30000); }
async function onMessage(ev) { if (!W || !P) return; if (!ev?.tags?.some?.((t) => t[0] === 'p' && t[1] === W.pub)) return; let m = null; try { m = JSON.parse(ev.content); } catch { return; } try { await P.onMessage(ev.pubkey, m); } catch (e) { log(`message ${m?.t ?? '?'} for ${m?.id ?? '?'}: ${e.message}`, 'e'); } }
const openChannel = (peer, amount, push = 0) => P.openChannel(peer, amount, push); const closeChannel = (ch) => P.closeChannel(ch); const forceClose = (ch, i, why) => P.forceClose(ch, i, why); const pay = (ch, amount, memo) => P.pay(ch, amount, memo);
// paying an invoice: an HTLC on a channel to the issuer, or to one of its hubs with the route; confirmed first
async function payInvoice(inv) { if (!node.synced) throw new Error('the node is not up to date yet'); if (inv.x && now() > inv.x) throw new Error('the invoice has expired'); const expiry = io.height() + 60;
  const direct = CH.find((c) => c.status === 'open' && c.peer === inv.p && P.room(c) >= inv.a); let plan = direct ? { ch: direct, via: null, amount: inv.a } : null;
  if (!plan) for (const hub of inv.r ?? []) { const c = CH.find((x) => x.status === 'open' && x.peer === hub && P.room(x) >= inv.a + (inv.f ?? 0)); if (c) { plan = { ch: c, via: hub, amount: inv.a + (inv.f ?? 0) }; break; } }
  if (!plan) throw new Error('no open channel to that node or to one of its hubs with enough on my side');
  const ok = await ask('Pay this invoice', [`${sats(inv.a)} to ${inv.p.slice(0, 16)}…${inv.m ? ` for "${inv.m}"` : ''}.`, plan.via ? `Through ${plan.via.slice(0, 16)}… on channel ${plan.ch.id}, with a hub fee of ${sats(plan.amount - inv.a)}: ${sats(plan.amount)} in all.` : `Directly on channel ${plan.ch.id}.`, `The payment is an HTLC that expires in 60 blocks (${hours(60)}); if the invoice is not settled by then the amount returns to you.`], 'Pay'); if (!ok) throw new Error('cancelled');
  await P.addHtlc(plan.ch, { amount: plan.amount, hash: inv.h, expiry, route: plan.via ? { to: inv.p } : null, memo: inv.m ?? null }); return plan; }

// ---- the chain: every funding output watched through the tab's own node, its value checked; a spend classified and answered by the protocol
const mature = (c) => !c.coinbase || (W.height != null && W.height + 1 - c.height >= 100);
function watch() { if (!W || !node.synced) return; tn.post({ type: 'coins', script: W.script }); for (const spk of new Set(CH.filter((c) => WATCHED.has(c.status)).map((c) => c.funding.spk))) tn.post({ type: 'coins', script: spk }); }
tn.on('coins', (m) => { if (!W) return; if (m.script === W.script) { W.coins = m.coins; W.height = m.height; renderBalances(); return; }
  for (const ch of CH.filter((c) => c.funding.spk === m.script && WATCHED.has(c.status))) { const key = `${ch.funding.txid}:${ch.funding.vout}`; const coin = m.coins.find((c) => c.key === key);
    if (coin) { if (coin.value !== ch.funding.value) { if (ch.status !== 'bad-funding') { ch.status = 'bad-funding'; io.save(); log(`channel ${ch.id}: the funding output holds ${sats(coin.value)}, not the ${sats(ch.funding.value)} declared; refused`, 'e'); } continue; }
      const conf = m.height - coin.height + 1; if (ch.status === 'funding') { ch.status = 'open'; ch.fundedHeight = coin.height; io.save(); notify('Channel open', `${ch.id}: ${sats(ch.funding.value)} funded at block ${n(coin.height)}`); } else if (!ch.fundedHeight) { ch.fundedHeight = coin.height; io.save(); } ch.conf = conf; continue; }
    if (ch.fundedHeight && (!spendAsked.has(ch.id) || now() - spendAsked.get(ch.id) > 60)) { spendAsked.set(ch.id, now()); tn.post({ type: 'spend', key, from: ch.fundedHeight, req: ch.id }); } }
  renderChannels(); });
tn.on('spend', async (m) => { if (typeof m.req === 'string' && m.req.endsWith(':penalty')) { const ch = byId(m.req.slice(0, -8)); if (ch && m.found && (ch.penalties ?? []).includes(m.txid)) { ch.status = 'punished'; io.save(); notify('Penalty confirmed', `${ch.id}: the penalty is in block ${n(m.height)}`); } return; }
  const ch = CH.find((c) => c.id === m.req); if (!ch) return; spendAsked.delete(ch.id); if (!m.found) return; try { await P.onSpend(ch, { txid: m.txid, height: m.height, hex: m.hex }); } catch (e) { log(`spend of ${ch.id}: ${e.message}`, 'e'); } });
tn.on('synced', () => { if (!W || !P) return; watch(); for (const ch of CH) { if (['closed-mine', 'closed-theirs', 'closed-theirs-alt'].includes(ch.status)) P.afterClose(ch).catch((e) => log(e.message, 'e')); if (ch.status === 'punishing' && ch.spentBy && ch.penalties?.length) { const t = P.theirCommitAt(ch, ch.closeState ?? 0); const vl = t.kinds.indexOf('to_local'); if (vl >= 0) tn.post({ type: 'spend', key: `${ch.spentBy.txid}:${vl}`, from: ch.spentBy.height, req: ch.id + ':penalty' }); } } if (!node.mempoolOn) { node.mempoolOn = true; tn.followMempool({ relays: OPT.relays }); } });

// ---- invoices: hitch1 + base64url of { p: node id, a: sats, m: memo, h: hash, r: hubs, f: hub fee, x: expires, i: id }; the preimage stays with the issuer
const b64u = (s) => btoa(unescape(encodeURIComponent(s))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); const unb64u = (s) => decodeURIComponent(escape(atob(s.replace(/-/g, '+').replace(/_/g, '/'))));
function makeInvoice(amount, memo) { if (!Number.isInteger(amount) || amount < 1000) throw new Error('at least 1,000 sat, a whole number'); const hubs = CH.filter((c) => c.status === 'open' && c.peerHubFee != null); const { preimage, inv } = P.invoice(amount, memo, [...new Set(hubs.map((c) => c.peer))], hubs.reduce((a, c) => Math.max(a, c.peerHubFee), 0)); INV.set(inv.h, { preimage, amount, memo: memo || undefined, x: inv.x }); saveInv(); return 'hitch1' + b64u(JSON.stringify(inv)); }
function parseInvoice(s) { s = s.trim(); if (!s.startsWith('hitch1')) throw new Error('not a Hitch invoice'); const inv = JSON.parse(unb64u(s.slice(6))); if (!/^[0-9a-f]{64}$/.test(inv.p ?? '') || !Number.isInteger(inv.a) || inv.a < 1 || !/^[0-9a-f]{64}$/.test(inv.h ?? '') || (inv.r != null && !(Array.isArray(inv.r) && inv.r.every((x) => /^[0-9a-f]{64}$/.test(x)))) || (inv.f != null && !(Number.isInteger(inv.f) && inv.f >= 0))) throw new Error('bad invoice'); return inv; }

// ---- rendering
const stLabel = (s) => ({ proposed: ['proposed', 'pend'], accepted: ['accepted, waiting for their signature', 'pend'], funding: ['funding, waiting for a block', 'pend'], open: ['open', 'open'], 'closing-asked': ['close asked', 'pend'], closing: ['closing', 'pend'], 'force-closing': ['force closing', 'pend'], 'closed-mine': ['closed by me, delay running', 'pend'], 'closed-theirs': ['closed by them', 'closed'], 'closed-theirs-alt': ['closed by them at a state I had signed', 'closed'], closed: ['closed', 'closed'], punishing: ['punishing a cheat', 'bad'], punished: ['closed: their cheat punished', 'closed'], 'closed-theirs-old': ['closed by them at an old state', 'bad'], 'spent-unknown': ['spent by an unknown transaction', 'bad'], 'bad-funding': ['funding output does not match: refused', 'bad'], abandoned: ['abandoned: never funded', 'closed'] }[s] ?? [s, '']);
const TERMINAL = new Set(['closed', 'punished', 'abandoned', 'closed-theirs-old', 'spent-unknown', 'bad-funding']);
const link = (txid, text) => `<a href="${EXPLORER}/tx/${esc(txid)}" target="_blank" rel="noopener" title="${esc(txid)}">${esc(text)}</a>`;
function renderChannels() { const el = $('chlist'); el.innerHTML = CH.length ? CH.slice().reverse().map((ch) => { const tot = ch.funding.value; const mine = myBal(ch), theirs = theirBal(ch); const [lbl, cls] = stLabel(ch.status); const inflight = P.htlcs(ch);
    const note = ch.pending ? ' · update pending' : ch.awaiting ? ' · waiting for their revocation' : ''; const links = [link(ch.funding.txid, 'funding'), ch.closeTxid ? link(ch.closeTxid, 'close') : '', ...(ch.penalties ?? []).map((p, i) => link(p, `penalty${ch.penalties.length > 1 ? ' ' + (i + 1) : ''}`)), ...Object.entries(ch.claimed ?? {}).map(([k2, v]) => link(v, k2.split(' ')[0]))].filter(Boolean).join(' · ');
    const buttons = ch.status === 'open' ? `<button class="q" data-act="close" data-ch="${esc(ch.id)}">Close</button><button class="q" data-act="force" data-ch="${esc(ch.id)}">Force close…</button>${OPT.dev && ch.n > 0 ? `<button class="q danger" data-act="cheat" data-ch="${esc(ch.id)}">Cheat (test)…</button>` : ''}` : ['closing-asked', 'funding'].includes(ch.status) ? `<button class="q" data-act="force" data-ch="${esc(ch.id)}">Force close…</button>` : '';
    const forget = TERMINAL.has(ch.status) ? `<button class="q" data-act="forget" data-ch="${esc(ch.id)}">Forget</button>` : `<button class="q" data-act="abandon" data-ch="${esc(ch.id)}" title="remove from this tab; read the warning first">Abandon…</button>`;
    return `<div class="chan"><div class="hd"><b>${esc(ch.id)}</b><span class="st ${cls}">${esc(lbl)}</span><span class="mut">with ${esc(ch.peer.slice(0, 12))}… · ${ch.role === 'a' ? 'I funded' : 'they funded'} ${sats(tot)} · state ${ch.n}${ch.conf ? ` · ${ch.conf} conf` : ''}${esc(note)}${inflight.length ? ` · ${inflight.length} htlc in flight (${sats(inflight.reduce((a, h) => a + h.amount, 0))})` : ''}${ch.role === 'b' && ch.peerHubFee != null ? ' · a hub' : ''}</span></div>
    <div class="bar2" title="mine ${sats(mine)} · theirs ${sats(theirs)}"><i style="width:${(mine / tot * 100).toFixed(1)}%"></i><i class="r" style="width:${(theirs / tot * 100).toFixed(1)}%"></i></div>
    <div class="row" style="margin-top:6px;font-size:12px"><span>mine <b class="mono">${sats(mine)}</b></span><span class="mut">theirs ${sats(theirs)}</span><span class="mut">${links}</span><span class="fill" style="flex:1"></span>${buttons}${forget}</div></div>`; }).join('') : '<div class="mut">no channels yet: open one to another node id, or wait for one to be opened to you</div>';
  el.querySelectorAll('button[data-act]').forEach((b) => { b.onclick = async () => { const ch = byId(b.dataset.ch); if (!ch) return; try {
    if (b.dataset.act === 'close') await closeChannel(ch);
    else if (b.dataset.act === 'force') { if (await ask('Force close', [`This publishes your latest commitment (state ${ch.n}). Your ${sats(myBal(ch))} come back to your key after ${ch.delay} blocks (${hours(ch.delay)}); theirs at once. It costs ${sats(ch.fee)} in fees.`, 'Use it when the other side is gone. A cooperative close is cheaper and faster when they answer.'], 'Force close', true)) await forceClose(ch); }
    else if (b.dataset.act === 'cheat') { if (await ask('Cheat, for the test', [`This publishes an OLD state (${ch.n - 1}) that you have revoked. If the other side is watching, it takes the whole channel: you lose ${sats(myBal(ch))}.`, 'This exists to show that cheating is punished.'], 'Publish the revoked state', true)) await forceClose(ch, ch.n - 1, 'CHEATING'); }
    else if (b.dataset.act === 'forget') { CH.splice(CH.indexOf(ch), 1); io.save(); }
    else if (b.dataset.act === 'abandon') { if (await ask('Abandon this channel?', [`It is ${stLabel(ch.status)[0]}. Removing it from this tab does not close it and does not return any funds.`, 'You lose the signed commitments and the revocation secrets: you can never force-close or claim from it again, and the other side can publish any old state without being punished.', 'Export a backup first if there is any doubt.'], 'Abandon', true)) { CH.splice(CH.indexOf(ch), 1); io.save(); } }
  } catch (e) { log(`${b.dataset.act} ${ch.id}: ${e.message}`, 'e'); } }; });
  $('push-ch').innerHTML = CH.filter((c) => c.status === 'open').map((c) => `<option value="${esc(c.id)}">${esc(c.id)} · mine ${sats(myBal(c))} · with ${esc(c.peer.slice(0, 10))}…</option>`).join('') || '<option value="">no open channel</option>';
  const busy = CH.some((c) => c.pending || c.awaiting || P.htlcs(c).length || ['force-closing', 'closed-mine', 'punishing', 'closed-theirs', 'closed-theirs-alt'].includes(c.status)); $('keepopen').hidden = !busy; renderBalances(); }
function renderBalances() { if (!W || !P) return; const open = CH.filter((c) => c.status === 'open'); const local = open.reduce((a, c) => a + myBal(c), 0), remote = open.reduce((a, c) => a + theirBal(c), 0); let avail = 0, imm = 0; for (const c of W.coins) (mature(c) ? (avail += c.value) : (imm += c.value));
  $('ch-local').textContent = money(local); $('ch-remote').textContent = money(remote); $('avail').textContent = money(avail); $('immature').textContent = money(imm); $('ch-count').textContent = `${open.length} open, ${CH.length} in all`; }
function render() { if (P) renderChannels(); }
addEventListener('beforeunload', (e) => { if (!P) return; const busy = CH.some((c) => c.pending || c.awaiting || P.htlcs(c).length || ['force-closing', 'closed-mine', 'punishing'].includes(c.status)); if (busy) { e.preventDefault(); e.returnValue = ''; } });

// ---- the page
document.querySelectorAll('.tool button[data-p]').forEach((b) => { b.onclick = () => { document.querySelectorAll('.tool button[data-p]').forEach((x) => x.classList.toggle('on', x === b)); document.querySelectorAll('.page').forEach((p) => p.classList.toggle('on', p.id === 'p-' + b.dataset.p)); }; });
document.querySelectorAll('#menu > div').forEach((m) => { m.onclick = (e) => { const open = m.classList.contains('open'); document.querySelectorAll('#menu > div').forEach((x) => x.classList.remove('open')); if (!open && !e.target.closest('.dd')) m.classList.add('open'); }; }); document.addEventListener('click', (e) => { if (!e.target.closest('#menu')) document.querySelectorAll('#menu > div').forEach((x) => x.classList.remove('open')); });
$('op-go').onclick = async () => { try { $('op-out').textContent = 'proposing…'; await openChannel($('op-peer').value.trim().toLowerCase(), Math.round(Number($('op-amt').value)), Math.round(Number($('op-push').value) || 0)); $('op-out').textContent = 'proposed; waiting for the other side'; } catch (e) { $('op-out').textContent = e.message; } };
$('push-go').onclick = async () => { try { const ch = byId($('push-ch').value); if (!ch) throw new Error('no open channel'); const amount = Math.round(Number($('push-amt').value)); if (!(await ask('Push to the channel', [`${sats(amount)} to ${ch.peer.slice(0, 16)}… on ${ch.id}, with no invoice: the other side just gets it.`], 'Push'))) return; await pay(ch, amount, $('push-memo').value.trim() || null); $('push-out').textContent = 'update sent; it is final when they acknowledge and you revoke'; } catch (e) { $('push-out').textContent = e.message; } };
$('pay-go').onclick = async () => { try { const inv = parseInvoice($('pay-inv').value); const r = await payInvoice(inv); $('pay-out').textContent = `paying ${sats(r.amount)} on ${r.ch.id}${r.via ? ` through ${r.via.slice(0, 12)}…` : ''}: the HTLC is out; the invoice settles it`; } catch (e) { $('pay-out').textContent = e.message; } };
$('pay-paste').onclick = async () => { try { $('pay-inv').value = await navigator.clipboard.readText(); } catch {} };
$('inv-go').onclick = () => { try { const s = makeInvoice(Math.round(Number($('inv-amt').value)), $('inv-memo').value.trim()); $('inv-out').value = s; const qr = qrcode(0, 'M'); qr.addData(s); qr.make(); $('inv-qr').innerHTML = qr.createSvgTag({ cellSize: 3, margin: 0 }); } catch (e) { $('inv-out').value = e.message; } };
$('inv-copy').onclick = async () => { try { await navigator.clipboard.writeText($('inv-out').value); $('inv-copy').textContent = 'Copied'; setTimeout(() => { $('inv-copy').textContent = 'Copy'; }, 1500); } catch {} };
$('m-nodeid').onclick = async () => { try { await navigator.clipboard.writeText(W.pub); notify('Copied', 'this node id is on the clipboard'); } catch {} };
$('m-readme').onclick = () => window.open('https://github.com/bitcoin-blake/hitch#readme', '_blank', 'noopener'); $('m-source').onclick = () => window.open('https://github.com/bitcoin-blake/hitch', '_blank', 'noopener');
$('m-about').onclick = () => $('about').showModal(); $('about-ok').onclick = () => $('about').close();
// ---- the window: dragged by its title bar, resized at any edge, zoomed by the green dot; geometry remembered; the tray when closed or minimized
const win = $('win'); const embedded = q.get('embedded') === '1' || q.get('frame') === '0';
const geom = { get: () => { try { return JSON.parse(LS.get('hitch:geometry') ?? 'null'); } catch { return null; } }, set: (g) => LS.set('hitch:geometry', JSON.stringify(g)) };
function applyGeometry(g) { win.style.left = g.x + 'px'; win.style.top = g.y + 'px'; win.style.width = g.w + 'px'; win.style.height = g.h + 'px'; }
function clampGeometry(g) { const W = innerWidth, H = innerHeight; g.w = Math.max(720, Math.min(g.w, W)); g.h = Math.max(420, Math.min(g.h, H)); g.x = Math.max(0, Math.min(g.x, W - Math.min(g.w, 120))); g.y = Math.max(0, Math.min(g.y, H - 40)); return g; }
function defaultGeometry() { const w = Math.min(1180, innerWidth - 48), h = Math.min(780, innerHeight - 48); return { x: Math.round((innerWidth - w) / 2), y: Math.round((innerHeight - h) / 2), w, h }; }
function layoutWindow() { if (embedded) return; const small = innerWidth < 1100 || innerHeight < 700; const saved = geom.get(); const max = saved?.max ?? small; win.classList.toggle('max', max); if (!max) applyGeometry(clampGeometry(saved?.g ?? defaultGeometry())); }
function saveGeometry() { if (embedded) return; const max = win.classList.contains('max'); const g = max ? (geom.get()?.g ?? defaultGeometry()) : { x: win.offsetLeft, y: win.offsetTop, w: win.offsetWidth, h: win.offsetHeight }; geom.set({ max, g }); }
function toggleZoom() { if (embedded) return; const max = !win.classList.contains('max'); win.classList.toggle('max', max); if (!max) applyGeometry(clampGeometry(geom.get()?.g ?? defaultGeometry())); saveGeometry(); }
if (!embedded) {
  layoutWindow(); addEventListener('resize', () => { if (!win.classList.contains('max')) applyGeometry(clampGeometry({ x: win.offsetLeft, y: win.offsetTop, w: win.offsetWidth, h: win.offsetHeight })); });
  $('dot-zoom').onclick = (e) => { e.stopPropagation(); toggleZoom(); }; $('wtitle').ondblclick = (e) => { if (!e.target.closest('.dots, .badge')) toggleZoom(); }; $('dot-close').onclick = (e) => { e.stopPropagation(); hideWindow(); }; $('dot-min').onclick = (e) => { e.stopPropagation(); hideWindow(); };
  // drag by the title bar
  $('wtitle').onpointerdown = (e) => { if (win.classList.contains('max') || e.target.closest('.dots, .badge')) return; const sx = e.clientX - win.offsetLeft, sy = e.clientY - win.offsetTop; const move = (ev) => applyGeometry(clampGeometry({ x: ev.clientX - sx, y: ev.clientY - sy, w: win.offsetWidth, h: win.offsetHeight })); const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); saveGeometry(); }; addEventListener('pointermove', move); addEventListener('pointerup', up); e.preventDefault(); };
  // resize at any edge or corner
  win.querySelectorAll(':scope > .rs').forEach((h) => { h.onpointerdown = (e) => { if (win.classList.contains('max')) return; const d = h.dataset.rs, x0 = e.clientX, y0 = e.clientY, g0 = { x: win.offsetLeft, y: win.offsetTop, w: win.offsetWidth, h: win.offsetHeight };
    const move = (ev) => { const dx = ev.clientX - x0, dy = ev.clientY - y0; const g = { ...g0 }; if (d.includes('e')) g.w = g0.w + dx; if (d.includes('s')) g.h = g0.h + dy; if (d.includes('w')) { g.w = g0.w - dx; g.x = g0.x + dx; } if (d.includes('n')) { g.h = g0.h - dy; g.y = g0.y + dy; } if (g.w < 720) { if (d.includes('w')) g.x = g0.x + g0.w - 720; g.w = 720; } if (g.h < 420) { if (d.includes('n')) g.y = g0.y + g0.h - 420; g.h = 420; } applyGeometry(g); };
    const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); saveGeometry(); }; addEventListener('pointermove', move); addEventListener('pointerup', up); e.preventDefault(); e.stopPropagation(); }; });
}

// ---- the tray: closing or minimizing the window keeps the node running and leaves a small card to come back through (Knots goes to the system tray the same way); inside Glass the host is told and keeps its dock
function hideWindow() { if (embedded) { try { parent.postMessage({ source: 'hitch', type: 'minimize' }, '*'); } catch {} return; } win.style.display = 'none'; unseen = 0; $('tray-badge').hidden = true; $('tray').hidden = false; trayRefresh(); }
function showWindow() { win.style.display = ''; $('tray').hidden = true; unseen = 0; $('tray-badge').hidden = true; }
function trayRefresh() { if ($('tray').hidden) return; const open = CH.filter((c) => c.status === 'open'); const sd = open.length ? ` · ${open.length} channel${open.length === 1 ? '' : 's'}, ${sats(open.reduce((a, c) => a + myBal(c), 0))}` : ''; $('tray-l').textContent = node.error ? 'error' : node.synced ? `up to date · ${n(node.height)}${sd}` : node.phase === 'fetch' ? 'fetching the snapshot' : node.phase === 'hash' ? 'checking the snapshot' : node.phase === 'verify' ? 'verifying the snapshot' : node.phase === 'sync' ? `syncing · ${n(node.height ?? 0)}` : 'starting'; $('tray-dot').className = node.error ? 'bad' : node.synced ? 'ok' : 'sync'; }
$('tray').onclick = () => showWindow(); setInterval(trayRefresh, 1000);

$('m-exit').onclick = () => hideWindow(); $('m-zoom').onclick = () => toggleZoom(); $('m-main').onclick = () => showWindow(); document.addEventListener('keydown', (e) => { if (e.ctrlKey && !e.shiftKey && e.key.toLowerCase() === 'm') { e.preventDefault(); showWindow(); } });
$('m-readme').onclick = () => window.open('https://github.com/bitcoin-blake/hitch#readme', '_blank', 'noopener'); $('m-source').onclick = () => window.open('https://github.com/bitcoin-blake/hitch', '_blank', 'noopener');
$('m-about').onclick = () => $('about').showModal(); $('about-ok').onclick = () => $('about').close();
$('m-options').onclick = () => { $('o-relays').value = OPT.relays.join('\n'); $('o-delay').value = OPT.delay; $('o-delayh').textContent = hours(OPT.delay); $('o-fee').value = OPT.fee; $('o-notify').checked = !!OPT.notify; $('o-dev').checked = !!OPT.dev; $('o-snapshot').value = SNAP_URL; $('o-blocks').value = BLOCKS_URL; $('o-address').value = W?.address ?? '…'; $('o-key').value = '•'.repeat(64); $('o-showkey').textContent = 'Show'; $('o-importkey').value = ''; $('o-keynote').textContent = W?.fromReef ? "Reef's key in this browser: back it up in Reef" : 'a key of this tab: copy it somewhere safe, the export below does not include it'; $('o-note').textContent = ''; $('options').showModal(); };
$('o-delay').oninput = () => { $('o-delayh').textContent = hours(Number($('o-delay').value) || 0); };
$('o-cancel').onclick = () => $('options').close();
$('o-showkey').onclick = () => { const shown = $('o-key').value !== '•'.repeat(64); $('o-key').value = shown ? '•'.repeat(64) : (W?.key ?? ''); $('o-showkey').textContent = shown ? 'Show' : 'Hide'; };
$('o-copykey').onclick = async () => { try { await navigator.clipboard.writeText(W?.key ?? ''); $('o-copykey').textContent = 'Copied'; setTimeout(() => { $('o-copykey').textContent = 'Copy'; }, 1500); } catch {} };
$('o-export').onclick = async () => { if (!(await ask('Export the channel documents', ['The file holds every signed commitment, every revocation secret and every preimage. Anyone who reads it can take what is yours in these channels. It does not hold the key.', 'Keep it where only you can read it.'], 'Export'))) return; const blob = new Blob([JSON.stringify({ hitch: 1, exported: now(), node: W.pub, channels: CH, invoices: [...INV] }, null, 1)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `hitch-channels-SECRET-${W.pub.slice(0, 8)}-${new Date().toISOString().slice(0, 10)}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 2000); };
$('o-import').onchange = async () => { const f = $('o-import').files[0]; if (!f) return; try { const d = JSON.parse(await f.text()); if (d.hitch !== 1 || !Array.isArray(d.channels)) throw new Error('not a Hitch backup'); if (d.node && d.node !== W.pub) throw new Error(`that backup is for node ${d.node.slice(0, 12)}…, this tab is ${W.pub.slice(0, 12)}…`); let added = 0, newer = 0; for (const c of d.channels) { const have = byId(c.id); if (!have) { CH.push(c); added++; } else if ((c.n ?? 0) > (have.n ?? 0)) { Object.assign(have, c); newer++; } } for (const [h, p] of d.invoices ?? []) if (!INV.has(h)) INV.set(h, typeof p === 'string' ? { preimage: p, amount: 0 } : p); saveInv(); io.save(); $('o-note').textContent = `imported: ${added} new channel(s), ${newer} brought forward; resyncing`; log(`backup imported: ${added} new, ${newer} newer`); P.resyncAll(true).catch(() => {}); } catch (e) { $('o-note').textContent = e.message; } };
$('o-ok').onclick = async () => { const relays = $('o-relays').value.split(/\s+/).filter((r) => /^wss?:\/\//.test(r)); OPT.relays = relays.length ? relays : DEFAULT_RELAYS; OPT.delay = Math.max(6, Math.min(144, Math.round(Number($('o-delay').value) || DEFAULT_DELAY))); OPT.fee = Math.max(100, Math.min(10000, Math.round(Number($('o-fee').value) || DEFAULT_FEE))); OPT.dev = $('o-dev').checked; const wantNotify = $('o-notify').checked; if (wantNotify && 'Notification' in window && Notification.permission === 'default') await Notification.requestPermission(); OPT.notify = wantNotify && Notification.permission === 'granted'; saveOptions();
  const s = $('o-snapshot').value.trim(), b = $('o-blocks').value.trim(); if (s) LS.set('hitch:snapshot', s); if (b) LS.set('hitch:blocks', b); const key = $('o-importkey').value.trim().toLowerCase(); if (key && !/^[0-9a-f]{64}$/.test(key)) { $('o-note').textContent = 'a key is 64 hex characters'; return; }
  if (key) { if (!(await ask('Replace the key', ['The channels in this tab belong to the current key; with another key they cannot be signed for. Only import a key when this tab has no live channels, or when restoring the key these channels were made with.'], 'Replace', true))) return; LS.set(W.fromReef ? 'reef:key' : 'hitch:key', key); }
  $('options').close(); location.search = ''; };
window.hitch = { tn, node, CH, INV, get W() { return W; }, get C() { return C; }, pay, openChannel, closeChannel, forceClose, payInvoice, makeInvoice };
try { await init(); setupPeer(); } catch (e) { log('could not start: ' + e.message, 'e'); }
render(); renderRelays(); log('Hitch started');
try { await tn.start(); } catch (e) { $('syncmsg').textContent = 'Error: could not start the node: ' + e.message; }
